version: v1.0
name: Heroku deployment
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu1804

blocks:
  - name: Deploy
    task:
      secrets:
        - name: heroku-api
        - name: heroku-api-key
      env_vars:
        - name: HEROKU_REMOTE
          value: https://git.heroku.com/tasklets.git
        - name: HEROKU_APP_NAME
          value: tasklets
      jobs:
        - name: Push code
          commands:
            - checkout --use-cache
            - ssh-keyscan -H heroku.com >> ~/.ssh/known_hosts
            - chmod 600 ~/.ssh/heroku_api
            - ssh-add ~/.ssh/heroku_api
            - git config --global url.ssh://git@heroku.com/.insteadOf https://git.heroku.com/
            - git remote add heroku $HEROKU_REMOTE
            - echo $HEROKU_REMOTE
            - git push heroku -f $SEMAPHORE_GIT_BRANCH:master
            - echo $SEMAPHORE_GIT_BRANCH
            - heroku run -a ${HEROKU_APP_NAME} rake db:migrate
            - heroku ps:restart
